### ISSUE TITLE
C# sample is not working

### ISSUE THREAD

**Issue by patv2learn** [DoubangoTelecom/KYC-Documents-Verif-SDK#11]
While trying the prebuild fine I am getting the following error. It looks like KYC-Documents-Verif-SDK-Models are missing but could not find where to download them. Please suggest. Thanks!

*[KYC_VERIF_SDK INFO]: Starting liveness sample...
*[COMPV INFO]: [KycVerifSdkEngine]Call: KycVerif::KycVerifSdkEngine::init
*[COMPV INFO]: [KycVerifSdkEngine]jsonConfig: {"debug_level": "info","debug_write_input_image_enabled": false,"debug_internal_data_path": ".","gpu_ctrl_memory_enabled": false,"num_threads": -1,"max_latency": -1,"max_batchsize": -1,"asm_enabled": true,"intrin_enabled": true,"openvino_device": "CPU","graph_type": "dense","graph_2passes_enabled": true,"graph_2ndpass_ocr_threshold": 0.9,"graph_2ndpass_umeyama_enabled": true,"ocr_2passes": true,"ocr_2ndpass_threshold": 0.9,"ocr_patch_antialias": true,"ocr_tunning_apply_patterns": true,"ocr_tunning_apply_whitelist": true,"ocr_tunning_apply_blacklist": true,"magsac_sigma": 2.0,"magsac_max_iters": 5000,"magsac_resampler": "prosac","tps_enabled": true,"tps_speed": 1,"tps_cost": "l2","stn_enabled": true,"detect_threshold": 0.3,"text_segmentation_type": "watershed","assets_folder": "../../../assets","openvino_activation": "auto"}
*[COMPV INFO]: [KycVerifSdkEngine]**** Copyright (C) 2011-2024 Doubango Telecom <https://www.doubango.org> ****
KycVerifDetection-SDK <https://github.com/DoubangoTelecom/KycVerifDetection-SDK> version 0.0.6

*[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
*[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #8
*[COMPV INFO]: [CompVBase] sizeof(float)= #4
*[COMPV INFO]: [CompVBase] Windows dwMajorVersion=6, dwMinorVersion=2
*[COMPV INFO]: Initializing window registery
*[COMPV INFO]: [ImageDecoder] Initializing image decoder...
*[COMPV INFO]: [CompVCpu] H: 'GenuineIntel', S: '', M: '', MN: ''
*[COMPV INFO]: [CompVBase] CPU features: (intel);[x86];[x64];mmx;sse;sse2;sse3;ssse3;sse41;sse42;avx;avx2;fma3;erms;bmi1;bmi2;popcnt;cmov;aes;rdrand;
*[COMPV INFO]: [CompVBase] CPU cores: online=#24, conf=#24
*[COMPV INFO]: [CompVBase] CPU cache1: line size: #64B, size :#48KB
*[COMPV INFO]: [CompVBase] CPU Phys RAM size: #16072GB
*[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
*[COMPV INFO]: [CompVBase] Binary type: X86_64
*[COMPV INFO]: [CompVBase] Intrinsic enabled
*[COMPV INFO]: [CompVBase] Assembler enabled
*[COMPV INFO]: [CompVBase] OS name: Windows
*[COMPV INFO]: [CompVBase] Math Fast Trig.: true
*[COMPV INFO]: [CompVBase] Math Fixed Point: true
*[COMPV INFO]: [CompVMathExp] Init
*[COMPV INFO]: [CompVBase] Default alignment: #64
*[COMPV INFO]: [CompVBase] Best alignment: #64
*[COMPV INFO]: [CompVBase] Heap limit: #822922KB (#803MB)
*[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
*[COMPV INFO]: /!\ Code in file 'compv_mem.cxx' in function 'compv::CompVMemZero_C' starting at line #508: Not optimized -> No SIMD implementation found
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=0,set=useless, threadId:0000000000009B74, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=13,set=useless, threadId:0000000000001998, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=15,set=useless, threadId:0000000000007DD0, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=7,set=useless, threadId:000000000000553C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #24 threads/#24 cores
*[COMPV INFO]: [CompVParallel] [Parallel] module initialized
*[COMPV INFO]: [CompVBase] [Base] modules initialized
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=10,set=useless, threadId:0000000000008D7C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=1,set=useless, threadId:0000000000007D3C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=20,set=useless, threadId:0000000000001BB8, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=3,set=useless, threadId:00000000000027D8, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=9,set=useless, threadId:0000000000008C58, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=12,set=useless, threadId:000000000000597C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=4,set=useless, threadId:00000000000059D4, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=17,set=useless, threadId:00000000000028F8, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=16,set=useless, threadId:0000000000008D4C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=19,set=useless, threadId:00000000000086E8, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=14,set=useless, threadId:0000000000008E68, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=5,set=useless, threadId:0000000000009618, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=18,set=useless, threadId:0000000000000AD4, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=22,set=useless, threadId:0000000000006094, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=8,set=useless, threadId:00000000000089CC, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=11,set=useless, threadId:0000000000009518, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
*[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
*[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
*[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
*[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
*[COMPV INFO]: [CompVGL] GL module initialized
*[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
*[COMPV INFO]: [CompVSharedLib] Loading shared library from nvcuda.dll
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=2,set=useless, threadId:000000000000322C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=23,set=useless, threadId:0000000000007AA4, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=21,set=useless, threadId:0000000000006C7C, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVAsyncTask11] compv::CompVAsyncTask11::run(coreId:requested=6,set=useless, threadId:00000000000090EC, kThreadSetAffinity:false) - ENTER
*[COMPV INFO]: [CompVGpu] Failed to open CUDA lib
*[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
*[COMPV INFO]: [CompVCamera] Camera plugin path: C:\Users\Dev\Desktop\KYC-Documents-Verif-SDK-main\KYC-Documents-Verif-SDK-main\binaries\windows\x86_64\CompVPluginMFoundation.dll
*[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
*[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
*[COMPV INFO]: [CompVDrawing] Drawing module initialized
*[COMPV INFO]: [CompVGpu] GPU enabled: true
*[COMPV INFO]: /!\ Code in file 'source\ultimate_base_engine.cxx' in function 'ultimateBase::UltBaseEngine::init' starting at line #75: Not optimized for GPU -> GPGPU computing not enabled or deactivated
*[COMPV INFO]: [UltBaseOpenCL] Trying to load [OpenCL.dll]
*[COMPV INFO]: [CompVSharedLib] Loading shared library from OpenCL.dll
*[COMPV INFO]: [UltBaseOpenCL] Loaded [OpenCL.dll], looksLikeValid: yes...
*[COMPV INFO]: [UltBaseOpenCLUtils] Selected platform vendor: Intel(R) Corporation
*[COMPV INFO]: [UltBaseOpenCLUtils] deviceCount=1
*[COMPV INFO]: [UltBaseOpenCLUtils] Device -> name: Intel(R) UHD Graphics 770, id: 0000024A5A3921C0
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT=1
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE=0
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_COMPUTE_UNITS=32
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS=3
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_SIZES=512, 512, 512,
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_GROUP_SIZE=512
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_CLOCK_FREQUENCY=1600 MHz
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE=64 B
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_SIZE=6741381120 B (6429 MB)
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_LOCAL_MEM_SIZE=65536 B (64 KB)
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_MEM_ALLOC_SIZE=3214 MB
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_PLATFORM_VERSION=OpenCL 3.0
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_VERSION=OpenCL 3.0 NEO
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DRIVER_VERSION=31.0.101.4953
*[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_OPENCL_C_VERSION=OpenCL C 1.2
***[COMPV ERROR]: function: "ultimateBase::UltBaseOpenCLUtils::init()"
file: "source\opencl\ultimate_base_opencl_utils.cxx"
line: "96"
message: [UltBaseOpenCLUtils] OpenCL operation failed (-30 -> CL_INVALID_VALUE) ->
***[COMPV ERROR]: function: "ultimateBase::UltBaseOpenCLUtils::init()"
file: "source\opencl\ultimate_base_opencl_utils.cxx"
line: "106"
message: Operation Failed (COMPV_ERROR_CODE_E_UNKNOWN) ->
*[COMPV INFO]: [UltBaseOpenCL] Failed to hook functions using [OpenCL.dll] library
*[COMPV INFO]: [UltTfEngine] Tensorflow version: 1.15.0
*[COMPV INFO]: [KycVerifSdkEnginePrivate]**** Copyright (C) 2011-2024 Doubango Telecom <https://www.doubango.org> ****
You're using an unlicensed version of KycVerifDetection-SDK <https://github.com/DoubangoTelecom/KYC-Documents-Verif-SDK>
without the rights to include the SDK in any form of commercial product. The result may be obfuscated with some chars replaced with *
*[COMPV INFO]: [CompVSharedLib] Loading shared library from nvcuda.dll
*[COMPV INFO]: [KycVerifSdkEnginePrivate] Failed to open CUDA lib
***[COMPV ERROR]: function: "compv::CompVFileUtils::read()"
file: "compv_fileutils.cxx"
line: "268"
message: [FileUtils] File at ../../../assets/KYC-Documents-Verif-SDK-Models/tensorflow_fp.txt.doubango is empty or doesn't exist
***[COMPV ERROR]: function: "ultimateBase::UltimateBaseDebugPrint()"
file: "C:\Projects\GitHub\ultimate\ultimateBase\lib\include\ultimate_base_debug.h"
line: "51"
message: [[Check Code]]Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> Failed to read file (RF)
***[COMPV ERROR]: function: "ultimateBase::UltimateBaseDebugPrint()"
file: "C:\Projects\GitHub\ultimate\ultimateBase\lib\include\ultimate_base_debug.h"
line: "51"
message: [[Check Code]]Operation Failed (COMPV_ERROR_CODE_E_FAILED_TO_READ_FILE) -> RF 001 failed
*[COMPV INFO]: [KycVerifSdkEnginePrivate]IC took 1 millis
***[COMPV ERROR]: function: "ultimateBase::UltimateBaseDebugPrint()"
file: "C:\Projects\GitHub\ultimate\ultimateBase\lib\include\ultimate_base_debug.h"
line: "51"
message: [KycVerifSdkEngine]Failed to initialize the engine

**Comment by DoubangoTelecom** [comment]
https://github.com/DoubangoTelecom/KYC-Documents-Verif-SDK?tab=readme-ov-file#checkout-source

**Comment by patv2learn** [comment]
I am an 8th-grade student in California and currently exploring programming and AI technologies. I am learning .NET (C#) and Python, with a keen interest in AI applications such as extracting data from images and PDF documents.

I do not have a company email account, but I can provide my school transcript if needed to verify my student status. Could you please let me know if I am eligible to access these private repos? If so, kindly let me know what details you require from me to proceed.
